<!doctype html>
<html lang=" en-US ">

<head>
    <meta charset="utf-8">
    <link rel="shortcut icon" type="image/x-icon" href="/favicon.ico?">
    <meta http-equiv="X-UA-Compatible" content="chrome=1">
    <link rel="stylesheet" href="/assets/css/style.css?v=a8db9f5ed3bfce1c7849f44f99b16371e6a97696">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js"></script>
    <script src="/assets/js/respond.js"></script>
    <!--[if lt IE 9]>
      <script src="//html5shiv.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
    <!--[if lt IE 8]>
    <link rel="stylesheet" href="/assets/css/ie.css">
    <![endif]-->

    
    <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no">
        
    
</head>

<body>
    <div id="header">
            <nav>
        <li><a href="https://github.com/ULL-MII-SYTWS-1920/ull-mii-sytws-1920.github.io/tree/master//tema2-async-1920/exercises/promises/exception-inside-promise/README.md" title="Edit this page at GitHub">üêô</a>
        </li>
        <li><a href="/search" title="search">&#x1F50D;</a></li>
       
        <li><a href="/resources.html" title="resources">&#x2699</a></li>
        <li><a href="/timetables.html" title="horarios">&#x1f5d3</a></li>
        <li><a href="/references.html" title="bibliografia">&#x1f4da</a></li>
        <li><a href="/practicas.html" title="pr√°cticas">&#x270d</a></li>
        

        <li><a href="/clases.html" title="clases">üë®‚Äçüè´</a></li>
        <li><a href="/index.html" title="Home page">&#x1f3e0</a></li>
        <li><a href="/tema0-presentacion/" title="Tema 0: Presentaci√≥n">0</a></li>
        <li><a href="/tema1-introduccion/" title="Tema 1: introducci√≥n">1</a></li>
        <li><a href="/tema2-async/" title="Tema 2: Async">2</a></li>
        <li><a href="/tema3-web/" title="Tema 3: Web">3</a></li>
        <li><a href="/tema4-devops/" title="Tema 4: Devops">4</a></li>
        
    </nav>

    </div>
    <!-- end header -->


    <div class="wrapper">

        <section>
           
<div id="title">
        <h1>Sistemas y Tecnolog√≠as Web: Servidor</h1>
        <p> Master de II. ULL. 1er cuatrimestre. 2020/2021</p>
        <hr>
        <span class="credits left">Organization <a href="https://github.com/ULL-MII-SYTWS-2021" target="_blank">ULL-MII-SYTWS-2021</a></span>
        <span class="credits left"> &nbsp; Classroom <a href="https://classroom.github.com/classrooms/68184806-ull-mii-sytws-2021" target="_blank">ULL-MII-SYTWS-2021</a></span>
        <span class="credits left"> &nbsp; Campus Virtual <a href="https://campusdoctoradoyposgrado.ull.es/course/view.php?id=2020111300" target="_blank">SYTWS</a></span>
        <span class="credits left"> &nbsp; Chat <a href="https://chat.google.com/u/1/room/AAAAp18fCE8" target="_blank">Chat</a></span>
        <span class="credits left"> &nbsp; Profesor <a href="https://www.ull.es/apps/guias/guias/view_teacher_niu/745/(%3FPcrguezl.*)/" target="_blank">Casiano</a></span>
    </div>

<!--

<div id="title">
    <h1>Sistemas y Tecnolog√≠as Web: Servidor</h1>
    <p> Master de II. ULL. 1er cuatrimestre. 2020/2021</p>
    <hr>
    <span class="credits left">Organization <a href="https://github.com/ULL-MII-SYTWS"
            target="_blank">ULL-MII-SYTWS</a></span>
    <span class="credits left"> &nbsp; Github Classroom <a
            href="https://classroom.github.com/classrooms/55384072-master-de-ingenieria-informatica-sistemas-y-tecnologias-web-servidor-classroom"
            target="_blank">SYTWS 19/20</a></span>
    <span class="credits left"> &nbsp; Campus Virtual <a
            href="https://campusvirtual.ull.es/1920/course/view.php?id=201913778" target="_blank">SYTWS
            19/20</a></span>
    <span class="credits left"> &nbsp; Profesor <a
            href="https://www.ull.es/apps/guias/guias/view_teacher_niu/588/(%3FPcrguezl.*)/"" target="
            _blank">Casiano</a></span>
</div>
-->    


           
            <h2 >Table of Contents</h2>
           
            <ul id="sytwstoc">
  <li><a href="#exercises-exceptions-and-promises">Exercises: Exceptions and Promises</a>
    <ul>
      <li><a href="#first-exercise-exception-inside-the-action-of-a-promise">First Exercise: Exception inside the action of a Promise</a></li>
      <li><a href="#second-exercise-exception-delayed-with-settimeout-inside-the-action-of-a-promise">Second Exercise: Exception Delayed with setTimeout inside the action of a Promise</a>
        <ul>
          <li><a href="#third-exercise-unhandled-rejection-event">Third Exercise: Unhandled Rejection Event</a></li>
          <li><a href="#summarizing">Summarizing</a></li>
        </ul>
      </li>
    </ul>
  </li>
</ul>
        

            <div class="container">
                <h1 id="exercises-exceptions-and-promises">Exercises: Exceptions and Promises</h1>

<h2 id="first-exercise-exception-inside-the-action-of-a-promise">First Exercise: Exception inside the action of a Promise</h2>

<p>(Blog view at <a href="https://ull-mii-sytws-1920.github.io/tema2-async/exercises/promises/exception-inside-promise/">https://ull-mii-sytws-1920.github.io/tema2-async/exercises/promises/exception-inside-promise/</a>)</p>

<p>Remember that the code of a <strong><a href="/tema2-async-1920/exercises/promises/exception-inside-promise/executor.html">promise executor</a></strong> and <strong>promise handlers</strong> has an ‚Äúinvisible <code class="language-plaintext highlighter-rouge">try..catch</code>‚Äù around it.</p>

<p>If an exception happens, it gets caught and treated as a rejection.</p>

<p><strong>Will the message <code class="language-plaintext highlighter-rouge">"Everything worked!"</code> appear?</strong> (See <a href="/tema2-async-1920/exercises/promises/exception-inside-promise/exception-inside.html">exception-inside.html</a>)</p>

<div class="language-js highlighter-rouge"><div class="highlight"><pre class="highlight"><code><table class="rouge-table"><tbody><tr><td class="rouge-gutter gl"><pre class="lineno">1
2
3
</pre></td><td class="rouge-code"><pre>   <span class="kd">let</span> <span class="nx">p</span> <span class="o">=</span> <span class="k">new</span> <span class="nb">Promise</span><span class="p">((</span><span class="nx">resolve</span><span class="p">,</span> <span class="nx">reject</span><span class="p">)</span>  <span class="o">=&gt;</span> <span class="p">{</span>
      <span class="k">throw</span> <span class="p">(</span><span class="k">new</span> <span class="nb">Error</span><span class="p">(</span><span class="dl">"</span><span class="s2">Que fallo!</span><span class="dl">"</span><span class="p">));</span>
    <span class="p">}).</span><span class="k">catch</span><span class="p">(</span> <span class="p">(</span><span class="nx">e</span><span class="p">)</span> <span class="o">=&gt;</span> <span class="nx">console</span><span class="p">.</span><span class="nx">log</span><span class="p">(</span><span class="dl">"</span><span class="s2">Everything worked! </span><span class="dl">"</span><span class="o">+</span><span class="nx">e</span><span class="p">));</span>
</pre></td></tr></tbody></table></code></pre></div></div>

<p><strong>What will be the ouput of this variant of the former code?</strong> (See <a href="/tema2-async-1920/exercises/promises/exception-inside-promise/exception-inside-2.html">exception-inside-2.html</a>)</p>

<div class="language-js highlighter-rouge"><div class="highlight"><pre class="highlight"><code><table class="rouge-table"><tbody><tr><td class="rouge-gutter gl"><pre class="lineno">1
2
3
4
5
6
7
</pre></td><td class="rouge-code"><pre>   <span class="kd">let</span> <span class="nx">p</span> <span class="o">=</span> <span class="k">new</span> <span class="nb">Promise</span><span class="p">((</span><span class="nx">resolve</span><span class="p">,</span> <span class="nx">reject</span><span class="p">)</span>  <span class="o">=&gt;</span> <span class="p">{</span>
      <span class="k">try</span> <span class="p">{</span>
        <span class="k">throw</span> <span class="p">(</span><span class="k">new</span> <span class="nb">Error</span><span class="p">(</span><span class="dl">"</span><span class="s2">Que fallo!</span><span class="dl">"</span><span class="p">));</span>
      <span class="p">}</span> <span class="k">catch</span> <span class="p">(</span><span class="nx">e</span><span class="p">)</span> <span class="p">{</span>
        <span class="nx">reject</span><span class="p">(</span> <span class="dl">"</span><span class="s2">tilin!</span><span class="dl">"</span><span class="p">);</span>
      <span class="p">}</span>
    <span class="p">}).</span><span class="k">catch</span><span class="p">(</span> <span class="p">(</span><span class="nx">e</span><span class="p">)</span> <span class="o">=&gt;</span> <span class="nx">console</span><span class="p">.</span><span class="nx">log</span><span class="p">(</span><span class="dl">"</span><span class="s2">Everything worked! </span><span class="dl">"</span><span class="o">+</span><span class="nx">e</span><span class="p">));</span>
</pre></td></tr></tbody></table></code></pre></div></div>

<p><strong>What will be the rejection value of the promise?</strong></p>

<h2 id="second-exercise-exception-delayed-with-settimeout-inside-the-action-of-a-promise">Second Exercise: Exception Delayed with setTimeout inside the action of a Promise</h2>

<p>(Blog at <a href="https://ull-mii-sytws-1920.github.io/tema2-async/exercises/promises/exception-inside-promise/">https://ull-mii-sytws-1920.github.io/tema2-async/exercises/promises/exception-inside-promise/</a>)</p>

<p><strong>What do you think? Will the <code class="language-plaintext highlighter-rouge">.catch</code> trigger?</strong></p>

<p>See the code in <a href="/tema2-async-1920/exercises/promises/exception-inside-promise/exception-delayed.html">exception-delayed.html</a>:</p>

<div class="language-js highlighter-rouge"><div class="highlight"><pre class="highlight"><code><table class="rouge-table"><tbody><tr><td class="rouge-gutter gl"><pre class="lineno">1
2
3
4
</pre></td><td class="rouge-code"><pre><span class="k">new</span> <span class="nb">Promise</span><span class="p">(</span><span class="kd">function</span><span class="p">(</span><span class="nx">resolve</span><span class="p">,</span> <span class="nx">reject</span><span class="p">)</span> <span class="p">{</span>
  <span class="nx">setTimeout</span><span class="p">(()</span> <span class="o">=&gt;</span> <span class="p">{</span>
    <span class="k">throw</span> <span class="k">new</span> <span class="nb">Error</span><span class="p">(</span><span class="dl">"</span><span class="s2">Whoops!</span><span class="dl">"</span><span class="p">);</span>
  <span class="p">},</span> <span class="mi">1000</span><span class="p">);</span>
</pre></td></tr></tbody></table></code></pre></div></div>
<p>Explain your answer.</p>

<p>Remember that the code of a <strong><a href="/tema2-async-1920/exercises/promises/exception-inside-promise/executor.html">promise executor</a></strong> and <strong>promise handlers</strong> has an ‚Äúinvisible <code class="language-plaintext highlighter-rouge">try..catch</code>‚Äù around it.</p>

<p>If an exception happens, it gets caught and treated as a rejection.</p>

<p>Thus, the former code is equivalent to this <a href="/tema2-async-1920/exercises/promises/exception-inside-promise/exception-delayed-2.html">exception-delayed-2.html</a>:</p>

<div class="language-js highlighter-rouge"><div class="highlight"><pre class="highlight"><code><table class="rouge-table"><tbody><tr><td class="rouge-gutter gl"><pre class="lineno">1
2
3
4
5
6
7
</pre></td><td class="rouge-code"><pre> <span class="k">new</span> <span class="nb">Promise</span><span class="p">(</span><span class="kd">function</span><span class="p">(</span><span class="nx">resolve</span><span class="p">,</span> <span class="nx">reject</span><span class="p">)</span> <span class="p">{</span>
      <span class="k">try</span> <span class="p">{</span>
        <span class="nx">setTimeout</span><span class="p">(()</span> <span class="o">=&gt;</span> <span class="p">{</span>
          <span class="k">throw</span> <span class="k">new</span> <span class="nb">Error</span><span class="p">(</span><span class="dl">"</span><span class="s2">Whoops!</span><span class="dl">"</span><span class="p">);</span>
        <span class="p">},</span> <span class="mi">1000</span><span class="p">);</span>
      <span class="p">}</span> <span class="k">catch</span> <span class="p">(</span><span class="nx">e</span><span class="p">)</span> <span class="p">{</span> <span class="nx">reject</span><span class="p">(</span><span class="nx">e</span><span class="p">);</span> <span class="p">}</span>
    <span class="p">}).</span><span class="k">catch</span><span class="p">(</span><span class="nx">alert</span><span class="p">);</span>
</pre></td></tr></tbody></table></code></pre></div></div>
<p>What is the sequences of actions taking place when this code executes?</p>

<p>Is the former code equivalent to this one (<a href="/tema2-async-1920/exercises/promises/exception-inside-promise/exception-delayed-3.html">exception-delayed-3.html</a>)? :</p>

<div class="language-js highlighter-rouge"><div class="highlight"><pre class="highlight"><code><table class="rouge-table"><tbody><tr><td class="rouge-gutter gl"><pre class="lineno">1
2
3
4
5
6
7
8
9
</pre></td><td class="rouge-code"><pre>   <span class="k">new</span> <span class="nb">Promise</span><span class="p">(</span><span class="kd">function</span><span class="p">(</span><span class="nx">resolve</span><span class="p">,</span> <span class="nx">reject</span><span class="p">)</span> <span class="p">{</span>
      <span class="nx">setTimeout</span><span class="p">(()</span> <span class="o">=&gt;</span> <span class="p">{</span>
        <span class="k">try</span> <span class="p">{</span>
          <span class="k">throw</span> <span class="k">new</span> <span class="nb">Error</span><span class="p">(</span><span class="dl">"</span><span class="s2">Whoops!</span><span class="dl">"</span><span class="p">);</span>
        <span class="p">}</span> <span class="k">catch</span><span class="p">(</span><span class="nx">e</span><span class="p">)</span> <span class="p">{</span>
          <span class="nx">reject</span><span class="p">(</span><span class="dl">'</span><span class="s1">rejected </span><span class="dl">'</span><span class="o">+</span><span class="nx">e</span><span class="p">);</span>
        <span class="p">}</span>
      <span class="p">},</span> <span class="mi">1000</span><span class="p">);</span>
    <span class="p">}).</span><span class="k">catch</span><span class="p">(</span><span class="nx">alert</span><span class="p">);</span>
</pre></td></tr></tbody></table></code></pre></div></div>

<p>I have these examples here:</p>

<div class="language-plaintext highlighter-rouge"><div class="highlight"><pre class="highlight"><code><table class="rouge-table"><tbody><tr><td class="rouge-gutter gl"><pre class="lineno">1
2
</pre></td><td class="rouge-code"><pre>~/.../promises/exception-inside-promise(master)]$ pwd -P
/Users/casiano/campus-virtual/1920/sytws1920/apuntes/tema2-async/exercises/promises/exception-inside-promise
</pre></td></tr></tbody></table></code></pre></div></div>

<h3 id="third-exercise-unhandled-rejection-event">Third Exercise: Unhandled Rejection Event</h3>

<p><strong>The ‚ÄúUnhandled rejection‚Äù event occurs when a promise error is not handled at the end of the microtask queue.</strong></p>

<p>Normally, if we expect an error, we add <code class="language-plaintext highlighter-rouge">.catch</code> to the promise chain to handle it:</p>

<div class="language-js highlighter-rouge"><div class="highlight"><pre class="highlight"><code><table class="rouge-table"><tbody><tr><td class="rouge-gutter gl"><pre class="lineno">1
2
3
4
5
</pre></td><td class="rouge-code"><pre><span class="kd">let</span> <span class="nx">promise</span> <span class="o">=</span> <span class="nb">Promise</span><span class="p">.</span><span class="nx">reject</span><span class="p">(</span><span class="k">new</span> <span class="nb">Error</span><span class="p">(</span><span class="dl">"</span><span class="s2">Promise Failed!</span><span class="dl">"</span><span class="p">));</span>
<span class="nx">promise</span><span class="p">.</span><span class="k">catch</span><span class="p">(</span><span class="nx">err</span> <span class="o">=&gt;</span> <span class="nx">alert</span><span class="p">(</span><span class="dl">'</span><span class="s1">caught</span><span class="dl">'</span><span class="p">));</span>

<span class="c1">// doesn't run: error handled</span>
<span class="nb">window</span><span class="p">.</span><span class="nx">addEventListener</span><span class="p">(</span><span class="dl">'</span><span class="s1">unhandledrejection</span><span class="dl">'</span><span class="p">,</span> <span class="nx">event</span> <span class="o">=&gt;</span> <span class="nx">alert</span><span class="p">(</span><span class="nx">event</span><span class="p">.</span><span class="nx">reason</span><span class="p">));</span>
</pre></td></tr></tbody></table></code></pre></div></div>

<p>What if we handle the error later? We are going to use Node.js this time.</p>

<div class="language-plaintext highlighter-rouge"><div class="highlight"><pre class="highlight"><code><table class="rouge-table"><tbody><tr><td class="rouge-gutter gl"><pre class="lineno">1
2
3
</pre></td><td class="rouge-code"><pre>~/.../promises/exception-inside-promise(master)]$ pwd -P
/Users/casiano/campus-virtual/1920/sytws1920/apuntes/tema2-async/exercises/promises/exception-inside-promise
~/.../promises/exception-inside-promise(master)]$ cat unhandled-promise-rejection.js 
</pre></td></tr></tbody></table></code></pre></div></div>

<p>Explain the behavior of this program:</p>

<div class="language-js highlighter-rouge"><div class="highlight"><pre class="highlight"><code><table class="rouge-table"><tbody><tr><td class="rouge-gutter gl"><pre class="lineno">1
2
3
4
5
6
7
8
9
10
11
12
</pre></td><td class="rouge-code"><pre><span class="cp">#!/usr/bin/env node
</span><span class="dl">'</span><span class="s1">use strict</span><span class="dl">'</span><span class="p">;</span>

<span class="nx">process</span><span class="p">.</span><span class="nx">on</span><span class="p">(</span><span class="dl">'</span><span class="s1">unhandledRejection</span><span class="dl">'</span><span class="p">,</span> <span class="nx">error</span> <span class="o">=&gt;</span> <span class="p">{</span>
  <span class="nx">console</span><span class="p">.</span><span class="nx">log</span><span class="p">(</span><span class="dl">'</span><span class="s1">unhandledRejection:</span><span class="dl">'</span><span class="p">,</span> <span class="nx">error</span><span class="p">.</span><span class="nx">message</span><span class="p">);</span>
<span class="p">});</span>

<span class="kd">let</span> <span class="nx">p</span> <span class="o">=</span> <span class="k">new</span> <span class="nb">Promise</span><span class="p">((</span><span class="nx">resolve</span><span class="p">,</span> <span class="nx">reject</span><span class="p">)</span> <span class="o">=&gt;</span> <span class="nx">reject</span><span class="p">(</span><span class="k">new</span> <span class="nb">Error</span><span class="p">(</span><span class="dl">'</span><span class="s1">woops</span><span class="dl">'</span><span class="p">)));</span>

<span class="nx">setTimeout</span><span class="p">(</span> 
  <span class="p">()</span> <span class="o">=&gt;</span> <span class="nx">p</span><span class="p">.</span><span class="k">catch</span><span class="p">(</span><span class="nx">error</span> <span class="o">=&gt;</span> <span class="nx">console</span><span class="p">.</span><span class="nx">log</span><span class="p">(</span><span class="dl">'</span><span class="s1">caught</span><span class="dl">'</span><span class="p">,</span> <span class="nx">error</span><span class="p">.</span><span class="nx">message</span><span class="p">)),</span>
  <span class="mi">1000</span><span class="p">);</span>
</pre></td></tr></tbody></table></code></pre></div></div>

<div class="language-plaintext highlighter-rouge"><div class="highlight"><pre class="highlight"><code><table class="rouge-table"><tbody><tr><td class="rouge-gutter gl"><pre class="lineno">1
2
3
4
</pre></td><td class="rouge-code"><pre>[~/.../event-loop/promise-ejemplo(master)]$ ./unhandled-promise-rejection.js 
unhandledRejection: woops
caught woops
(node:107) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 1)
</pre></td></tr></tbody></table></code></pre></div></div>

<p>V√©ase tambi√©n
<a href="https://javascript.info/microtask-queue#unhandled-rejection">https://javascript.info/microtask-queue#unhandled-rejection</a>
para una versi√≥n de este programa  en el cliente/browser</p>

<h3 id="summarizing">Summarizing</h3>

<ol>
  <li><code class="language-plaintext highlighter-rouge">.catch</code> handles errors in promises of all kinds: be it a <code class="language-plaintext highlighter-rouge">reject()</code> call, or an error thrown in a handler.</li>
  <li>We should place <code class="language-plaintext highlighter-rouge">.catch</code> exactly in places where we want to handle errors and know how to handle them.</li>
  <li>It‚Äôs ok not to use <code class="language-plaintext highlighter-rouge">.catch</code> at all, if there‚Äôs no way to recover from an error.</li>
  <li>In any case we should have the <code class="language-plaintext highlighter-rouge">unhandledrejection</code> event handler to track unhandled errors</li>
</ol>


            </div>
                        <details>
                <summary><h2>Comment with GitHub Utterances</h2></summary>
                <script src="https://utteranc.es/client.js"
        repo="ULL-MII-SYTWS-1920/ull-mii-sytws-1920.github.io"
        issue-term="pathname"
        label="SYTWS"
        theme="dark-blue"
        crossorigin="anonymous"
        async>
</script>
            </details>
            
            <details>
                <summary>
                   <h2>Comment with Disqus</h2> 
                </summary>              
                



<div id="disqus_thread">
    thread de discusion
</div>
<script>

/**
*  RECOMMENDED CONFIGURATION VARIABLES: 
EDIT AND UNCOMMENT THE SECTION BELOW TO INSERT DYNAMIC VALUES FROM YOUR PLATFORM OR CMS.
*  LEARN WHY DEFINING THESE VARIABLES IS IMPORTANT: 
       https://disqus.com/admin/universalcode/#configuration-variables*/

/*
var disqus_config = function () {
   this.page.url = PAGE_URL;  // Replace PAGE_URL with your page's canonical URL variable
   this.page.identifier = PAGE_IDENTIFIER; // Replace PAGE_IDENTIFIER with your page's unique identifier variable
};
*/

(function() { // DON'T EDIT BELOW THIS LINE
  var d = document, s = d.createElement('script');
  s.src = 'https://https-ull-mii-sytws-1920-github-io.disqus.com/embed.js';
  s.setAttribute('data-timestamp', +new Date());
   (d.head || d.body).appendChild(s);
})();

</script>

<noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
                            

 

            </details>

            <!-- -->
            <!-- end bar -->

            <!-- Mathjax Support  -->
            <script src='https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js?config=TeX-MML-AM_CHTML' async></script>


        </section>
    </div>

    
</body>

</html>
